load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "sfcore",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "sfcore_unit_tests",
    crate = ":sfcore",
    edition = "2021",
)

rust_test(
    name = "foundations",
    srcs = ["tests/foundations.rs"],
    edition = "2021",
    deps = [":sfcore"] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
