#!/usr/bin/env python3
"""Generate crates/notation/src/glyphs.rs from src/glyphs.js.

The JS table uses short keys; this writes the SMuFL names. Outlines and
boxes are copied unchanged, in Bravura font units (1000 per em, 4 staff
spaces per em, y up).

Usage: python3 crates/notation/tools/gen_glyphs.py  (from the repo root)
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[3]
SRC = ROOT / "src" / "glyphs.js"
DST = ROOT / "crates" / "notation" / "src" / "glyphs.rs"

SMUFL = {
    "gClef": "gClef", "gClef8vb": "gClef8vb",
    "nhBlack": "noteheadBlack", "nhHalf": "noteheadHalf", "nhWhole": "noteheadWhole",
    "flag8Up": "flag8thUp", "flag8Down": "flag8thDown",
    "flag16Up": "flag16thUp", "flag16Down": "flag16thDown",
    "flat": "accidentalFlat", "natural": "accidentalNatural", "sharp": "accidentalSharp",
    "restWhole": "restWhole", "restHalf": "restHalf", "restQuarter": "restQuarter",
    "rest8": "rest8th", "rest16": "rest16th", "dot": "augmentationDot", "mrH": "restHBar",
}
for d in range(10):
    SMUFL["t%d" % d] = "timeSig%d" % d


def table(js, name):
    m = re.search(r"const %s=(\{.*?\});" % name, js, re.S)
    if not m:
        raise SystemExit("no %s in %s" % (name, SRC))
    return json.loads(m.group(1))


def const_name(s):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s).upper()


js = SRC.read_text()
paths, boxes = table(js, "GLYPHS"), table(js, "GLYPH_BOX")
out = [
    "//! Bravura glyph outlines (Steinberg, SIL Open Font License 1.1), by SMuFL name.",
    "//! Generated by crates/notation/tools/gen_glyphs.py from src/glyphs.js; do not edit.",
    "//! Units: font units, `UNITS_PER_EM` per em, 4 staff spaces per em, y up.",
    "",
    "/// Font units per em (4 staff spaces).",
    "pub const UNITS_PER_EM: f64 = 1000.0;",
    "",
    "/// One glyph: SMuFL name, SVG path data, bounding box [x0, y0, x1, y1].",
    "#[derive(Clone, Copy, Debug)]",
    "pub struct Glyph {",
    "    pub name: &'static str,",
    "    pub path: &'static str,",
    "    pub bbox: [i16; 4],",
    "}",
    "",
]
names = []
for key, d in paths.items():
    sm = SMUFL[key]
    c = const_name(sm)
    names.append(c)
    b = ", ".join(str(v) for v in boxes[key])
    out.append("pub const %s: Glyph = Glyph { name: %s, path: %s, bbox: [%s] };" % (c, json.dumps(sm), json.dumps(d), b))
out.append("")
out.append("/// Every glyph in the table.")
out.append("pub const ALL: &[Glyph] = &[%s];" % ", ".join(names))
out.append("")
out.append("/// The time-signature digits 0-9.")
out.append("pub const TIME_SIG: [Glyph; 10] = [%s];" % ", ".join("TIME_SIG%d" % d for d in range(10)))
DST.write_text("\n".join(out) + "\n")
print("wrote %d glyphs to %s" % (len(names), DST))
