/* ---------------- styles: each fixes form, meter, tempo, modes, idiom and arrangement ----------------
   tempo is the felt beat per meter (6/8 = dotted quarter). band keys match song.band. lead = instrument for breaks. */
const FORMS={
 vc:{label:'verse and chorus',steps:[['intro',{inst:4}],['verse',{n:4}],['chorus',{n:4}],['verse',{n:4}],['chorus',{same:1}],['bridge',{n:'2 to 4'}],['chorus',{same:1}],['outro',{inst:3}]]},
 vcBreaks:{label:'verse and chorus with instrumental breaks',steps:[['intro',{inst:4,brk:1}],['verse',{n:4}],['chorus',{n:4}],['interlude',{inst:8,brk:1}],['verse',{n:4}],['chorus',{same:1}],['interlude',{inst:4,brk:1}],['chorus',{same:1}],['outro',{n:'1 to 2',tag:1}]]},
 strophic:{label:'strophic ballad',note:'No chorus. The story runs across the verses; each verse moves it forward.',steps:[['intro',{inst:4}],['verse',{n:4}],['verse',{n:4}],['verse',{n:4}],['interlude',{inst:4}],['verse',{n:4}],['verse',{n:4}],['outro',{inst:2}]]},
 refrain:{label:'verses with a refrain line',note:'No chorus. Every verse ends with the same refrain line, word for word; the verses change what it means.',steps:[['intro',{inst:4}],['verse',{n:4}],['verse',{n:4}],['verse',{n:4}],['interlude',{inst:4}],['verse',{n:4}],['outro',{inst:2}]]},
 aaba:{label:'AABA (32-bar song form)',note:'The A sections share one melody; the B section (bridge) contrasts in harmony and angle.',steps:[['intro',{inst:4}],['verse',{n:4}],['verse',{n:4}],['bridge',{n:4}],['verse',{n:4}],['interlude',{inst:4}],['bridge',{same:1}],['verse',{n:4}],['outro',{inst:2}]]},
 chorusFirst:{label:'chorus first',note:'Open cold on the chorus, then tell the story.',steps:[['chorus',{n:4}],['verse',{n:4}],['chorus',{same:1}],['verse',{n:4}],['chorus',{same:1}],['chorus',{same:1}],['outro',{inst:3}]]},
 prechorus:{label:'verse, pre-chorus, chorus',steps:[['intro',{inst:4}],['verse',{n:4}],['prechorus',{n:2}],['chorus',{n:4}],['verse',{n:4}],['prechorus',{same:1}],['chorus',{same:1}],['bridge',{n:'2 to 4'}],['chorus',{same:1}],['outro',{inst:3}]]},
 waltzBreaks:{label:'verse and chorus with a break',steps:[['intro',{inst:4,brk:1}],['verse',{n:4}],['chorus',{n:4}],['interlude',{inst:4,brk:1}],['verse',{n:4}],['chorus',{same:1}],['chorus',{same:1}],['outro',{inst:3}]]},
 blues12:{label:'12-bar blues',note:'Each verse is three lines, and each of those lines spans FOUR chord entries (4 bars), making 12 bars: I7 I7 I7 I7 | IV7 IV7 I7 I7 | V7 IV7 I7 V7 (variants welcome). Line two repeats line one, perhaps with a small change; line three answers or twists it.',bars:4,steps:[['intro',{inst:4}],['verse',{n:3}],['verse',{n:3}],['interlude',{inst:8,brk:1}],['verse',{n:3}],['verse',{n:3}],['outro',{inst:4}]]},
 hymn:{label:'hymn stanzas',note:'Stanzas in a hymn meter (8.6.8.6 or 8.7.8.7 syllables per line), plainly sung; the tag is one closing line.',steps:[['intro',{inst:4}],['verse',{n:4}],['verse',{n:4}],['interlude',{inst:4}],['verse',{n:4}],['verse',{n:4}],['outro',{n:'1',tag:1}]]}
};
const B=(o)=>Object.assign({bass:true,harmonyGuitar:false,harp:false,violin:false,choir:false,harmonies:false,doubles:false},o);
const STYLES={
 appalachian:{label:'Appalachian ballad',meters:['3/4','4/4'],tempo:{'3/4':[72,96],'4/4':[66,88]},modes:['mixolydian','dorian','minor','major'],idiom:'modal and spare: two or three chords (I, bVII, IV or i, bVII, v), a long story sung plainly',guitar:'fingerpick',drums:'none',band:B({bass:false,violin:true}),forms:['strophic','refrain'],lead:'violin'},
 oldtime:{label:'Old-time string band',meters:['4/4'],tempo:{'4/4':[100,128]},modes:['major','mixolydian'],idiom:'I, IV, V with drive; the fiddle takes the breaks',guitar:'strum',drums:'none',band:B({harmonyGuitar:true,violin:true,harmonies:true}),forms:['vcBreaks','refrain'],lead:'violin'},
 bluegrass:{label:'Bluegrass',meters:['4/4','3/4'],tempo:{'4/4':[108,140],'3/4':[100,132]},modes:['major'],idiom:'I, IV, V with the occasional II major; high lonesome harmony on the chorus; fiddle and guitar trade breaks',guitar:'strum',drums:'none',band:B({harmonyGuitar:true,violin:true,harmonies:true}),forms:['vcBreaks'],lead:'both'},
 cowboy:{label:'Western and cowboy song',meters:['3/4','4/4'],tempo:{'3/4':[80,104],'4/4':[76,100]},modes:['major'],idiom:'open-range major harmony, I, IV, V and the II7 on the way home',guitar:'travis',drums:'brushes',band:B({harmonyGuitar:true,violin:true,harmonies:true}),forms:['vc','waltzBreaks','strophic'],lead:'violin'},
 bakersfield:{label:'Bakersfield country',meters:['4/4'],tempo:{'4/4':[112,144]},modes:['major','mixolydian'],idiom:'shuffle-driven I, IV, V with a bVII; a twangy guitar break',guitar:'strum',drums:'full',band:B({harmonyGuitar:true,violin:true,harmonies:true,doubles:true}),forms:['vcBreaks','vc','chorusFirst'],lead:'guitar'},
 texas:{label:'Texas songwriter',meters:['4/4','3/4'],tempo:{'4/4':[78,104],'3/4':[84,108]},modes:['major','minor'],idiom:'plain chords, long verses, detail-heavy storytelling',guitar:'travis',drums:'brushes',band:B({harmonyGuitar:true}),forms:['refrain','strophic','aaba'],lead:'guitar'},
 cajun:{label:'Cajun waltz',meters:['3/4'],tempo:{'3/4':[104,138]},modes:['major'],idiom:'two or three chords (I, V, IV); the fiddle answers the voice',guitar:'strum',drums:'soft',band:B({violin:true,harmonies:true}),forms:['waltzBreaks'],lead:'violin'},
 zydeco:{label:'Creole and zydeco two-step',meters:['4/4'],tempo:{'4/4':[108,132]},modes:['major','mixolydian'],idiom:'I, IV, V with a push; a call you can shout back',guitar:'strum',drums:'full',band:B({harmonyGuitar:true,violin:true,choir:true,harmonies:true,doubles:true}),forms:['chorusFirst','vcBreaks'],lead:'both'},
 acadian:{label:'Acadian fiddle song',meters:['6/8','3/4'],tempo:{'6/8':[62,80],'3/4':[96,120]},modes:['major','mixolydian'],idiom:'kitchen-party harmony, I, IV, V; the fiddle leads the dance',guitar:'strum',drums:'soft',band:B({violin:true,harmonies:true}),forms:['vcBreaks','refrain'],lead:'violin'},
 broadside:{label:'English broadside ballad',meters:['6/8','3/4','4/4'],tempo:{'6/8':[52,68],'3/4':[80,104],'4/4':[76,98]},modes:['major','dorian','mixolydian'],idiom:'a tune for a news story or a scandal, simple diatonic harmony',guitar:'fingerpick',drums:'none',band:B({bass:false,violin:true}),forms:['strophic','refrain'],lead:'violin'},
 scottish:{label:'Scottish ballad',meters:['3/4','4/4'],tempo:{'3/4':[66,88],'4/4':[60,80]},modes:['dorian','mixolydian','minor'],idiom:'modal and dignified: i, bVII, bVI or I, bVII',guitar:'arpeggio',drums:'none',band:B({harp:true,violin:true}),forms:['strophic','refrain','aaba'],lead:'violin'},
 irishair:{label:'Irish air',meters:['3/4','6/8'],tempo:{'3/4':[60,80],'6/8':[44,60]},modes:['major','dorian','mixolydian'],idiom:'a long-breathed tune over few chords; ornament rather than harmony',guitar:'arpeggio',drums:'none',band:B({harp:true,violin:true}),forms:['strophic','aaba'],lead:'violin'},
 irishpub:{label:'Irish drinking song',meters:['6/8','4/4'],tempo:{'6/8':[68,84],'4/4':[104,128]},modes:['major','mixolydian'],idiom:'a chorus the whole room can shout, I, IV, V',guitar:'strum',drums:'soft',band:B({violin:true,choir:true,harmonies:true,doubles:true}),forms:['vc','chorusFirst','vcBreaks'],lead:'violin'},
 welsh:{label:'Welsh hymn tune',meters:['4/4','3/4'],tempo:{'4/4':[60,78],'3/4':[66,84]},modes:['major'],idiom:'four-part hymn harmony, cadences on I, a lift to vi',guitar:'arpeggio',drums:'none',band:B({harp:true,choir:true,harmonies:true}),forms:['hymn'],lead:'guitar'},
 breton:{label:'Breton dance song',meters:['4/4','6/8'],tempo:{'4/4':[104,128],'6/8':[68,84]},modes:['dorian','minor'],idiom:'modal drone harmony, call and response in the lines',guitar:'strum',drums:'soft',band:B({violin:true,harmonies:true}),forms:['refrain','vcBreaks'],lead:'violin'},
 blues:{label:'Delta and Piedmont blues',meters:['4/4'],tempo:{'4/4':[70,100]},modes:['mixolydian','major'],idiom:'dominant-seventh harmony, I7, IV7, V7',guitar:'travis',drums:'brushes',band:B({harmonyGuitar:true}),forms:['blues12'],lead:'guitar'},
 gospel:{label:'Gospel',meters:['4/4','6/8'],tempo:{'4/4':[72,104],'6/8':[50,66]},modes:['major'],idiom:'I, IV, V, vi with passing sevenths; a call and a response',guitar:'arpeggio',drums:'soft',band:B({choir:true,harmonies:true,doubles:true}),forms:['chorusFirst','vc','prechorus'],lead:'guitar'},
 revival:{label:'1960s folk revival',meters:['4/4','3/4'],tempo:{'4/4':[92,124],'3/4':[92,116]},modes:['major','minor'],idiom:'three chords and the truth; a duo harmony on the refrain',guitar:'fingerpick',drums:'none',band:B({bass:false,harmonies:true}),forms:['refrain','vc','strophic'],lead:'guitar'},
 laurel:{label:'Laurel Canyon',meters:['4/4','3/4'],tempo:{'4/4':[72,100],'3/4':[80,104]},modes:['major','mixolydian'],idiom:'open tunings and maj7, sus2, add9 colors; stacked harmony',guitar:'arpeggio',drums:'soft',band:B({harmonyGuitar:true,harmonies:true,doubles:true}),forms:['vc','prechorus','aaba'],lead:'guitar'},
 nashville:{label:'Nashville country waltz',meters:['3/4'],tempo:{'3/4':[84,112]},modes:['major'],idiom:'I, IV, V with a II7 and a walk-up; fiddle fills',guitar:'strum',drums:'brushes',band:B({harmonyGuitar:true,violin:true,harmonies:true}),forms:['waltzBreaks','vc'],lead:'violin'},
 americana:{label:'Present-day Americana',meters:['4/4','3/4'],tempo:{'4/4':[72,112],'3/4':[84,110]},modes:['major','minor','mixolydian'],idiom:'open, ringing harmony; a vi or a bVII where it hurts or lifts',guitar:'strum',drums:'soft',band:B({harmonyGuitar:true,violin:true,harmonies:true,doubles:true}),forms:['vc','prechorus','chorusFirst','aaba'],lead:'both'},
 shanty:{label:'Sea shanty',meters:['4/4','6/8'],tempo:{'4/4':[96,124],'6/8':[60,76]},modes:['major','dorian'],idiom:'call and response: the shantyman sings a line, the crew answers with a short refrain line; I and V',guitar:'strum',drums:'none',band:B({bass:false,choir:true,harmonies:true,doubles:true,violin:true}),forms:['refrain','chorusFirst'],lead:'violin'}
};
function formText(fk){const F=FORMS[fk];const bars=F.bars||2;let i=0;const cnt={};
  const lines=F.steps.map(([t,o])=>{i++;cnt[t]=(cnt[t]||0)+1;const nm=t==='interlude'?'interlude':t;
    if(o.inst)return `${i}. ${nm}: instrumental${o.brk?' break (the lead instrument plays the tune)':''}, ${o.inst} chord entries, no lines`;
    if(o.same)return `${i}. ${nm}: repeat, written {"type":"${t}","same":true}`;
    if(o.tag)return `${i}. outro: a tag of ${o.n} lyric line${o.n==='1'?'':'s'} (a closing echo of the hook), ${bars} chord entries per line`;
    return `${i}. ${nm} ${cnt[t]}: ${o.n} lines, ${bars} chord entries per line`;});
  return {label:F.label,note:F.note||'',text:lines.join('\n'),bars};}
function styleDirection(key){const p=a=>a[Math.floor(Math.random()*a.length)];const k=key&&STYLES[key]?key:p(Object.keys(STYLES));const S=STYLES[k];
  const meter=p(S.meters),[lo,hi]=S.tempo[meter];const form=p(S.forms);
  return {style:k,label:S.label,idiom:S.idiom,mode:p(S.modes),meter,tempoLo:lo,tempoHi:hi,form,guitar:S.guitar,drums:S.drums,band:S.band,lead:S.lead,
    world:Math.random()<0.12?p(['fado','Cape Verdean coladeira','Mexican son jarocho','Tex-Mex conjunto','French chanson','klezmer','Malian desert blues']):null};}
function applyStyle(song,key){const S=STYLES[key];if(!S)return song;song.style=key;song.guitar=S.guitar;song.breakLead=S.lead;
  song.band=Object.assign({},S.band,{drums:S.drums});const r=S.tempo[song.meter];if(r)song.tempo=Math.round(clamp(song.tempo,r[0]*0.9,r[1]*1.1));return song;}
